version: '3'
services:
  a:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet

  b:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet
      
  c:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet
      
  d:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet
      
  e:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet
      
  f:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet
      
  g:
    image: davidbetz/recursivecall
    environment:
      - DEBUG=trace
    volumes:
      /lib64/:/lib64/
    networks:
      - recursivecallnet
    ports:
      - "3000:3000"

networks:
  recursivecallnet:
    driver: bridge
    driver_opts:
      encrypted: ""
