version: '3'
services:
  a:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet
    ports:
      - "3000:3000"

  b:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  c:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  d:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  e:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  f:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  g:
    image: davidbetz/recursivecall
    deploy:
      replicas: 3
    environment:
      - DEBUG=trace
    networks:
      - recursivecallnet

networks:
  recursivecallnet:
    driver: overlay
    driver_opts:
      encrypted: ""

