version: '3'
services:
  a:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=a
      - DEBUG=trace
    networks:
      - recursivecallnet

  b:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=b
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  c:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=c
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  d:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=d
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  e:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=e
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  f:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=f
      - DEBUG=trace
    networks:
      - recursivecallnet
      
  g:
    image: davidbetz/recursivecall:healthcheck-latest
    deploy:
      replicas: 3
    environment:
      - NAME=g
      - DEBUG=trace
    networks:
      - recursivecallnet
    ports:
      - "3000:3000"

networks:
  recursivecallnet:
    driver: overlay
    driver_opts:
      encrypted: ""

